# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/xenial64" # ubuntu 16.04 LTS
  # config.vm.box = "ubuntu/bionic64" # ubuntu 18.04 LTS
  # config.vm.box = "ubuntu/focal64"  # ubuntu 20.04 LTS
  config.vm.box = "ubuntu/jammy64"    # ubuntu 22.04 LTS

  # config.vm.disk :disk, size: "10GB", primary: true

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 3000, host: 8030, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/project"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "file", source: "./aliases.zsh", destination: "~/.aliases.zsh"
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y openjdk-8-jdk unzip
  #   sudo snap install flutter --classic
  #   export ANDROID_SDK_ROOT=/usr/lib/android-sdk
  #   mkdir -p $ANDROID_SDK_ROOT
  #   cd $ANDROID_SDK_ROOT
  #   wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
  #   unzip commandlinetools-linux-6858069_latest.zip
  #   PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
  #   cd $ANDROID_SDK_ROOT/
  #   mv $ANDROID_SDK_ROOT/cmdline-tools tools
  #   mkdir mv $ANDROID_SDK_ROOT/cmdline-tools tools/.
  # SHELL
end
